services:
  - type: web
    name: url-to-mp3
    runtime: python
    repo: https://github.com/your-username/url-to-mp3
    plan: free
    region: oregon
    buildCommand: |
      apt-get update && \
      apt-get install -y ffmpeg && \
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: "10000"
    version: "1"

